version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/console/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Los_Angeles"
    cooldown:
      default-days: 7
    groups:
      patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/console/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Los_Angeles"
    cooldown:
      default-days: 7
    groups:
      patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
