; UserGame.ini managed by Docker.
; Edit this single file for all map and partition UserGame settings.
; Docker applies the correct values to each server when maps start or restart.

[Map:DeepDesert_1:/Script/DuneSandbox.PvpPveSettings]
m_bShouldForceEnablePvpOnAllPartitions=False

[Partition:DeepDesert_1:8:/Script/DuneSandbox.DuneGameMode]
bPvPEnabled=True

bServerPVE=False

[Partition:DeepDesert_1:8:/Script/DuneSandbox.PvpPveSettings]
+m_PvpEnabledPartitions=8

[Partition:DeepDesert_1:8:ConsoleVariables]
Bgd.ServerDisplayName=Deep Desert PvP

[Partition:DeepDesert_1:31:/Script/DuneSandbox.DuneGameMode]
bPvPEnabled=False

bServerPVE=True

[Partition:DeepDesert_1:31:/Script/DuneSandbox.PvpPveSettings]
+m_PveEnabledPartitions=31

[Partition:DeepDesert_1:31:ConsoleVariables]
Bgd.ServerDisplayName=Deep Desert PvE

[Partition:Survival_1:1:/Script/DuneSandbox.InventorySystemSettings]
PlayerInventoryStartingVolumeCapacity=2000

[Partition:Survival_1:1:ConsoleVariables]
Bgd.ServerDisplayName=Sietch Sayyadina
Bgd.ServerLoginPassword=WaterOfLife*Fremen22
