listeners.tcp = none
listeners.ssl.default = 5672

ssl_options.cacertfile = /etc/rabbitmq/cacert.pem
ssl_options.certfile   = /etc/rabbitmq/cert.pem
ssl_options.keyfile    = /etc/rabbitmq/key.pem
ssl_options.verify     = verify_none
ssl_options.fail_if_no_peer_cert = false

management.tcp.port = 15672
loopback_users.guest = false

auth_backends.1 = cache
auth_cache.cache_ttl = 5000
auth_cache.cached_backend = http

auth_http.http_method   = post
auth_http.user_path     = http://dune-text-router:5059/v0/auth/user
auth_http.vhost_path    = http://dune-text-router:5059/v0/auth/vhost
auth_http.resource_path = http://dune-text-router:5059/v0/auth/resource
auth_http.topic_path    = http://dune-text-router:5059/v0/auth/topic
